#%RAML 1.0 Trait
headers:
     client_id:
       displayName: Client ID
       description: Client identifier for authentication
       type: string
       required: true
     client_secret:
       displayName: Client Secret
       description: Client secret for authentication
       type: string
       required: true