#%RAML 1.0 NamedExample
{
 "SSLC_MarksheetCertificate": "base64_encoded_data_here",
  "UG_DegreeCertificate": "base64_encoded_data_here",
  "Certificate1_Mulesoft": "base64_encoded_data_here",
  "Certificate2_Mulesoft": "base64_encoded_data_here",
  "Certificate3_Mulesoft": "base64_encoded_data_here",
  "AadhaarCard": "base64_encoded_data_here",
  "BackgroundVerification1": "base64_encoded_data_here"
}
