#%RAML 1.0 DataType
type: array
items:
  type: object
  properties:
    sickLeave:
      type: string
      required: true
      description: Allocation of sick leave
    personalLeave:
      type: string
      required: true
      description: Allocation of personal leave