#%RAML 1.0 NamedExample
{
  "EmployeeID": "DW001",
  "Age": "22",
  "WorkPhoneNumber": "1234567890",
  "NickName": "",
  "Role": "MuleSoft Developer",
  "EmploymentType": "Full-time",
  "EmployeeStatus": "Active",
  "SourceOfHire": ""
}
