#%RAML 1.0 Library
traits:
  "errorResponse": !include exchange_modules/8f1968ec-ae72-424d-be0d-d4e44abb1bd1/errorresponse/1.0.0/errorresponse.raml
  

  "security": !include exchange_modules/8f1968ec-ae72-424d-be0d-d4e44abb1bd1/security-client_id-enforcement/1.0.0/security-client_id-enforcement.raml


types:

  updateForgotPassword: !include ../dataType/updateForgotPassword.raml
  postSingup: !include ../dataType/postSingup.raml
  postSignin: !include ../dataType/postSignin.raml
  otpGenerate: !include ../dataType/otpGenerate.raml
  otpResend : !include ../dataType/OTP_resend_dataType.raml
 
