#%RAML 1.0 NamedExample
{
  "EmployeeID": "DW001",
  "SSLC_MarksheetCertificate": "base64_encoded_data_here",
  "UG_DegreeCertificate": "base64_encoded_data_here",
  "Certificate1_Mulesoft": "base64_encoded_data_here",
  "Certificate2_Mulesoft": "base64_encoded_data_here",
  "Certificate3_Mulesoft": "base64_encoded_data_here",
  "AadhaarCard": "base64_encoded_data_here",
  "BackgroundVerification1": "base64_encoded_data_here",
  "PreviousEmployerJoiningLetters": "base64_encoded_data_here",
  "PreviousEmployerAppointmentOrders": "base64_encoded_data_here",
  "OtherTechCertifications": "base64_encoded_data_here",
  "PanCard": "base64_encoded_data_here",
  "HSC_PUC_CertificateMarksheet": "base64_encoded_data_here",
  "PG_DegreeCertificate": "base64_encoded_data_here",
  "Last_3_Month_Payslips": "base64_encoded_data_here",
  "PreviousEmployerRelievingLetter": "base64_encoded_data_here",
  "OfferLetter": "base64_encoded_data_here",
  "Resume": "base64_encoded_data_here"
}
