#%RAML 1.0 NamedExample

[
    {
        "LeaveType": "Sick Leave",
        "Available": "10.5 days",
        "Booked": "1.5 days"
    },
    {
        "LeaveType": "Personal Leave",
        "Available": "3.5 days",
        "Booked": "2.5 days"
    }
]