http:
 host: "0.0.0.0"
 port: "8081"
 path: "api/*"


 
HumanResources:
 protocol: "http"
 host: "human-resources-sapi.us-e2.cloudhub.io"
 basePath: "/api/"
 signup: "signup"
 forgetPossword: "signin/forgetPossword"
 
notification:
 host: "notifications-sapi.us-e2.cloudhub.io"
 basePath: "/api/"
 emailPath: "notifications?type=Email"
 
os:
  Entryttl: "1"
  expirationInterval: "1"
  otp: 
    Entryttl: "1"
    expirationInterval: "1"
    
 
 
