#%RAML 1.0
title: notification-sapi
description: Notification System API for sending notifications to Users over mail
version: v1
mediaType: application/json
protocols: [HTTP , HTTPS]

uses:
  Library: commonLibrary.raml
  


types:
  post-notification-request: !include resources/dataTypes/post-email-request.raml

/notifications:
    post:
      queryParameters:
        type:
          type: string
          enum: [Email]
          description: Creates a new notification over SMTP
      is:  Library.common-error    
      body:
        application/json:
          type: post-notification-request
          example: !include resources/examples/post-email-request-example.raml
      responses:
        200:
          body:
            application/json:
              example:
                !include resources/examples/post-email-response-example.raml
                      