#%RAML 1.0 DataType


  type: object
  properties:
    SSLC_MarksheetCertificate:
      type: string
      required: false
    UG_DegreeCertificate:
      type: string
      required: false
    Certificate1_Mulesoft:
      type: string
      required: false
    Certificate2_Mulesoft:
      type: string
      required: false
    Certificate3_Mulesoft:
      type: string
      required: false
    AadhaarCard:
      type: string
      required: false
    BackgroundVerification1:
      type: string
      required: false
    PreviousEmployerJoiningLetters:
      type: string
      required: false
    PreviousEmployerAppointmentOrders:
      type: string
      required: false
    OtherTechCertifications:
      type: string
      required: false
    PanCard:
      type: string
      required: false
    HSC_PUC_CertificateMarksheet:
      type: string
      required: false
    PG_DegreeCertificate:
      type: string
      required: false
    Last_3_Month_Payslips:
      type: string
      required: false
    PreviousEmployerRelievingLetter:
      type: string
      required: false
    OfferLetter:
      type: string
      required: false
    Resume:
      type: string
      required: false
     
