http:
 host: "0.0.0.0"
 port: "8081"
 path: "/api/*"
 
attendSapi:
  host: "attendance-sapi.us-e2.cloudhub.io"
  entryMethod: "POST"
  entryPath: "/entry"
  totalhrsMethod: "GET"
  totalhrsPath: "/totalHours"
  basePath: "/api/attendance"
  
leaveTracker:
  host: "leavetracker-papi.us-e2.cloudhub.io"
  holidayMethod: "GET"  
  holidayPath: "/holidays"
  basePath: "/api/Leave"
until:
  retries: "1"
  millisecs: "6000"

 
 
  
 