#%RAML 1.0 DataType
  type: object
  properties:
    
    Aadhaar:
      type: string
      required: false
    PassportNumber:
      type: string
      required: false
    PassportValidUntil:
      type: date-only
      required: false
