#%RAML 1.0 NamedExample
  {
  "EmployeeID": "DW001",
  "FirstName": "john",
  "LastName": "",
  "Department": "IT",
  "Designation": "MuleSoft Developer",
  "Competency": "",
  "DateOfBirth": "2002-06-05",
  "Gender": "Male",
  "PersonalEmailAddress": "john.doe@gamil.com",
  "FathersName": "Michael Doe",
  "Pincode": "123456",
  "MiddleName": "Robert",
  "EmailAddress": "john.doe@Dwinsoft.in",
  "Location": "New York",
  "DateOfJoining": "2020-01-10",
  "PAN": "ABCDE1234F",
  "AddressLine1": "123 Main Street",
  "AddressLine2": "Apt 101",
  "City": "New York",
  "AccountHoldersName": "John Doe",
  "AccountNumber": "1234567890",
  "PaymentMode": "Direct Deposit",
  "IFSCCode": "ABCD0123456",
  "PersonalMobileNumber": "1234567890"
}
